apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-vodcotqo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/go-vodcotqo:azure-5080494620a23a3a8ef8b9dd339e0fcf3110f920
          name: container-image
